<?php

/**
 * @file
 * Main file for tsitaatcom quote of the day module.
 */

/**
 * Implements hook_menu().
 */
function tsitaatcom_qotd_menu() {
  $items = array();

  $items['admin/config/content/tsitaatcom/quote-of-the-day'] = array(
    'title' => 'Quote of the Day',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tsitaatcom_qotd_settings_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'tsitaatcom_qotd.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['tsitaatcom-qotd-quote-of-the-day-cron-2'] = array(
    'title' => 'Quote of the Day',
    'description' => '',
    'page callback' => array('tsitaatcom_qotd_cron'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Menu hook for tsitaatcom-qotd-quote-of-the-day-cron.
 */
function tsitaatcom_qotd_cron() {
  ob_start();
  print '$_SERVER' . "\n";
  print_r($_SERVER);
  print '$_GET' . "\n";
  print_r($_GET);
  $printr = ob_get_contents();
  ob_end_clean();
  mail ('hkirsman@gmail.com', 'Tsitaat FB\'i', $printr);
  // For some reason Google found out about our secret
  // url /tsitaatcom-qotd-quote-of-the-day-cron.
  // It shouldn't because it's MENU_CALLBACK. Now'll add this GET parameter
  // and see what happens.
  if (isset($_GET['no_search_bots_please']) && $_GET['no_search_bots_please'] == 1) {
    $quote = _tsitaatcom_qotd_set_quote_of_the_day();
    _tsitaatcom_qotd_post_qotd_to_facebook($quote[0]);
    _tsitaatcom_qotd_post_qotd_to_twitter($quote[0]);
  }
}

/**
 * Get random quote that is not yet been a quote of the day.
 * @return array
 *   Quote
 */
function _tsitaatcom_qotd_set_quote_of_the_day() {
  // Build the initial query.
  $query = TsitaatcomQuote::buildQuery(array(
    'range' => array(
      'start' => 0,
      'length' => 1,
    ),
  ));

  // Get all quotes that are not in tsitaatcom_qotd table (aka not chosen as
  // quote of the day yet).
  $query->leftJoin('tsitaatcom_qotd', 'tsitaatcom_qotd', 'n.nid = tsitaatcom_qotd.quote_id');
  $query->condition('tsitaatcom_qotd.quote_id', NULL, 'IS');

  // Ignore Adolf Hitler.
  // @todo: there are more of these on the 'ignore list'.
  $query->condition('field_qa_url_alias.field_qa_url_alias_value', 'adolf_hitler', '!=');

  // Reset order by so orderRandom() could work.
  $order =& $query->getOrderBy();
  $order = array();

  $query->orderRandom();

  $quotes = TsitaatcomQuote::getQuotes(array('skip_drupal_not_found' => TRUE), $query);

  if (count($quotes) === 0) {
    watchdog(
      'tsitaatcom_qotd',
      'There are no quotes left for "Quote of the day"!',
      array(),
      WATCHDOG_NOTICE
    );
  }
  elseif (count($quotes) < 10) {
    watchdog(
      'tsitaatcom_qotd',
      'There are less 10 quotes to choose from for "Quote of the day"! Please check!',
      array(),
      WATCHDOG_NOTICE
    );
  }

  if (count($quotes) > 0) {
    db_insert('tsitaatcom_qotd')
      ->fields(array(
        'quote_id' => $quotes[0]['quote_nid'],
      ))
      ->execute();
  }

  return $quotes;
}

/**
 * Implements hook_block_info().
 */
function tsitaatcom_qotd_block_info() {
  $blocks = array();

  $blocks['tsitaatcom_qotd_block_delta'] = array(
    'info' => t('Quote of the Day'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function tsitaatcom_qotd_block_view($delta = '') {
  if (function_exists($delta . '_view')) {
    return call_user_func($delta . '_view');
  }
}

/**
 * Block code to view tsitaatcom_qotd_block_delta.
 * @return array
 *   Block data.
 */
function tsitaatcom_qotd_block_delta_view() {
  $block = array('subject' => '', 'content' => '');

  $block['content'] = _tsitaatcom_qotd_get_latest_quote_of_the_day();

  return $block;
}

/**
 * Get HTML for quote of the day.
 *
 * @return string
 *   Quote of the day
 */
function _tsitaatcom_qotd_get_latest_quote_of_the_day() {
  $out = '';

  $result = db_query("SELECT quote_id FROM {tsitaatcom_qotd} ORDER BY id DESC LIMIT 1;");

  if ($result) {
    $quote_nid = $result->fetchAssoc();

    $quotes = TsitaatcomQuote::getQuotes(array(
      'quote_nid' => $quote_nid,
    ));

    $out = TsitaatcomQuote::getQuotesRender($quotes, array(
      'disable_author_image' => TRUE,
      'disable_quote_info' => TRUE,
    ));
  }

  return $out;
}

/**
 * Post quote to Facebook.
 */
function _tsitaatcom_qotd_post_qotd_to_facebook($quote) {
  if (variable_get('tsitaatcom_qotd_fb_enabled', 0) === 1) {
    require_once DRUPAL_ROOT . '/sites/all/libraries/facebook-php-sdk/src/facebook.php';

    $config['appId'] = variable_get('tsitaatcom_qotd_fb_app_id');
    $config['secret'] = variable_get('tsitaatcom_qotd_fb_secret');
    // fileUpload is optional.
    $config['fileUpload'] = FALSE;
    $fb = new Facebook($config);

    print_r($config);

    $first_tag = explode(',', $quote['tags']);
    $first_tag = str_replace('_', ' ', trim($first_tag[0]));

    $message = trim($quote['quote_raw']) . "\n\n";
    $message .= $quote['quote_author_name_rendered_only_name'] . "\n";
    $message .= 'www.tsitaat.com/' . $quote['quote_nid'];

    $params_fb = array(
      'access_token' => variable_get('tsitaatcom_qotd_fb_token'),
      'message' => $message,
      'caption' => ' ',
    );

    // @todo: photo could be added with this:
    // $params_fb['picture'] = 'http://www.tsitaat.com/cache/images/foo.jpg;

    try {
      $ret = $fb->api('/' . variable_get('tsitaatcom_qotd_fb_wall') . '/feed', 'POST', $params_fb);
      echo 'Successfully posted to Facebook Personal Profile';
    }
    catch (Exception $e) {
      echo $e->getMessage();
    }
  }
}

/**
 * Shorten Twitter message so it could be sent, also add 3 dots to the end.
 */
function _tsitaatcom_qotd_shorten_twitter_message($message, $url) {
  $out = $message . ' ' . $url;
  while (drupal_strlen($out) > 136) {
    $message = drupal_substr($message, 0, -1);
    $out = $message . '... ' . $url;
  }
  return $out;
}

/**
 * Post quote to Twitter.
 */
function _tsitaatcom_qotd_post_qotd_to_twitter($quote) {
  if (variable_get('tsitaatcom_qotd_twitter_enabled', 0) === 1) {
    require_once DRUPAL_ROOT . '/sites/all/libraries/codebird-php/src/codebird.php';

    \Codebird\Codebird::setConsumerKey(variable_get('tsitaatcom_qotd_twitter_consumer_key'), variable_get('tsitaatcom_qotd_twitter_consumer_secret'));
    $cb = \Codebird\Codebird::getInstance();
    $cb->setToken(variable_get('tsitaatcom_qotd_twitter_access_token'), variable_get('tsitaatcom_qotd_twitter_access_token_secret'));

    $url = 'www.tsitaat.com/' . $quote['quote_nid'];
    $params_tw = array(
      'status' => _tsitaatcom_qotd_shorten_twitter_message($quote['quote_raw'], $url),
    );

    // @todo: image could be uploaded with:
    // $params_tw['media[]'] = '/var/www/tsitaat/__files/foo.jpg';

    $reply = $cb->statuses_update($params_tw);
    print_r($reply);
  }
}
